{% set name = "moe" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moe-{{ version }}.tar.gz
  sha256: 843ead1566f6f03130fd801a2ffcbede0f235466ff9d68c4643969dd7f190f78

build:
  entry_points:
    - moe = moe.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - poetry-core >=1.1.0a6
    #Might be switched to regular poetry again in the future
  run:
    - alembic >=1.4.2,<2.0.0
    - dynaconf >=3.1.4,<4.0.0
    - moe_mediafile >=0.10.1,<0.11.0
    - musicbrainzngs >=0.7.1,<0.8.0
    - pluggy >=0.13.1,<0.14.0
    - python >=3.9,<3.12
    - pyyaml >=5.3.1,<6.0.0
    - questionary >=1.9.0,<2.0.0
    - rich >=12.5.1,<13.0.0
    - sqlalchemy >=1.4.15,<2.0.0
    - unidecode >=1.2.0,<2.0.0
    - mccabe >=0.7.0,<0.8.0

test:
  imports:
    - moe
  commands:
    - pip check
    - moe --help
  requires:
    - pip

about:
  home: https://github.com/MoeMusic/Moe
  summary: The ultimate tool for managing your music library.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MoeMusic/Moe
  doc_url: https://mrmoe.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
