{% set name = "moe" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Moe-{{ version }}.tar.gz
  sha256: 656a58141acc50beed8de81a9cd632492a235f044219dfc44ff86db6e0560709

build:
  entry_points:
    - moe = moe.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - poetry
  run:
    - alembic >=1.4.2,<2.0.0
    - dynaconf >=3.1.4,<4.0.0
    - mediafile >=0.6.0,<0.7.0
    - musicbrainzngs >=0.7.1,<0.8.0
    - pluggy >=0.13.1,<0.14.0
    - python >=3.6,<3.10
    - pyyaml >=5.3.1,<6.0.0
    - questionary >=1.9.0,<2.0.0
    - sqlalchemy >=1.4.15,<2.0.0
    - unidecode >=1.2.0,<2.0.0

test:
  imports:
    - moe
  commands:
    - pip check
    - moe --help
  requires:
    - pip

about:
  home: https://github.com/MoeMusic/Moe
  summary: The ultimate tool for managing your music library.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MoeMusic/Moe
  doc_url: https://mrmoe.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
